### ISSUE TITLE
Format the endpoint parameters in a table

### ISSUE THREAD

**Issue by francoischalifour** [Springworks/swagger-md#54]
I think we could improve the current Markdown output to make it more readable.
## Feature proposal

> Format the endpoint parameters in a table
### GET /pets/{id}

| Type | Name | Type | Schema | Description |
| --- | --- | --- | --- | --- |
| path | **id** | `integer` | - | ID of pet to fetch |
### POST /pets

| Type | Name | Type | Schema | Description |
| --- | --- | --- | --- | --- |
| body | **body** | `object` | `name` (string)<br>`age` (integer) _(optional)_ | Params for new pet |
## Solution
- Edit `generateParameters()` in order to generated a Markdown table instead of a list.
- Map over the schema list and join the properties with `<br>` in the cell
- Add some tests

I've already implemented the feature and added the tests.

Let me know if you like the idea so I can send a PR.

**Comment by sommestad** [comment]
We actually discussed this the other day; a possible drawback with a table is that it could get very wide (and unreadable) if there are nested objects (with multiple levels). Any creative suggestions on how to handle that?

https://github.com/Springworks/swagger-md/releases/tag/v1.5.0 added support for nested objects. Is that compatible with your change, to see how it works?

**Comment by sommestad** [comment]
Another creative alternative could be to render schema on pretty JSON format instead of a table or list... (?)

**Comment by dbrockman** [comment]
I was going to change URL and query params to tables. The body might still be easier to read as a nested list (?)
